excel:
  template:
    first-row: 4

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
#        format_sql: true
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
