spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gonghak98_v2
    username: test
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  servlet:
    multipart:
      max-file-size: 50KB
      max-request-size: 1MB
